# Generated by Django 4.2.4 on 2024-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_msg', models.TextField()),
            ],
        ),
    ]
