# Generated by Django 4.2.4 on 2024-03-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notification', '0002_trainernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerNotification',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
