# Generated by Django 4.2.4 on 2023-11-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_guest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest_user',
            old_name='user_name',
            new_name='phone',
        ),
    ]
