# Generated by Django 4.2.4 on 2024-02-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
