# Generated by Django 4.2.4 on 2024-02-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0003_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
    ]
