from .dashboard.update_address import update_address
#from .dashboard.update_address_view import update_address_view
from .password.change_password import change_password
from user_auth.views.dashboard.dashboard_options.total_orders import total_orders
from user_auth.views.dashboard.dashboard_options.pending_orders import pending_orders
from user_auth.views.dashboard.dashboard_options.order_completed import order_completed
from user_auth.views.dashboard.dashboard_options.cash_on_deliverys import cash_on_deliverys
from user_auth.views.dashboard.dashboard_options.paid_delivery import paid_delivery
from user_auth.views.dashboard.deactivate_account import deactivate_account
from user_auth.views.authentication.custom_authentication import CustomAuthenticationBackend

