from payments.views.amar_pay.aamar_pay import initial_payment
from payments.views.amar_pay.payment_success import success
from payments.views.amar_pay.product_purchased import product_purchased
from payments.views.invoice import invoice
from payments.views.cash_on_delivery.cash_on_delivery import cash_on_delivery
from payments.views.cash_on_delivery.cash_on_delivary_for_single_product import cash_on_delivary_for_single_product