#from cart.views.old_add_to_cart import add_to_cart
from cart.views.add_to_cart import add_to_cart
from cart.views.cart_view import cart_view
from cart.views.increase_item import increase_cart
from cart.views.decrease_item import decrease_cart
from cart.views.remove_item import remove_from_cart
from cart.views.clear_cart import clear_cart
from cart.views.add_to_wish_list import add_to_wish_list
from cart.views.view_wishlist import view_wish_list
from cart.views.delete_wish_list import delete_wish_list