# Generated by Django 4.2.4 on 2023-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('purchased', models.BooleanField(default=False)),
                ('guest_user', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatedd', models.DateTimeField(auto_now=True)),
                ('select_order_stats', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Cancle'), (2, 'Deliver'), (1, 'Pending')], null=True)),
            ],
        ),
    ]
