# Generated by Django 4.2.4 on 2023-11-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_item_cart_product_item_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product_item',
            new_name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
