# Generated by Django 4.2.4 on 2023-12-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_size_variant_products_product_size'),
        ('cart', '0004_cart_color_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_size_variant'),
        ),
    ]
