# Generated by Django 4.2.4 on 2023-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_product_item_cart_item_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='paymentId',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='select_order_stats',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Cancle'), (2, 'Deliver'), (1, 'Pending')], null=True),
        ),
    ]
