# Generated by Django 4.2.4 on 2023-11-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_orderid_cart_paymentid_cart_select_order_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='paymentId',
        ),
    ]
