# Generated by Django 4.2.4 on 2023-12-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_color_variant'),
        ('cart', '0007_remove_cart_color_remove_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_color_variant'),
        ),
    ]
