# Generated by Django 4.2.4 on 2023-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guest_user',
            field=models.BooleanField(default=False),
        ),
    ]
