# Generated by Django 4.2.4 on 2024-01-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_coupon_code'),
        ('cart', '0008_cart_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon_code'),
        ),
    ]
