# Generated by Django 4.2.4 on 2024-01-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_coupon_code'),
        ('cart', '0009_cart_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='guest_user',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon_Code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='purchased',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='select_order_stats',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updatedd',
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='cart.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products')),
                ('product_Size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_size_variant')),
            ],
        ),
    ]
