# Generated by Django 4.2.4 on 2024-02-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_wish_list_user_alter_wish_list_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish_list',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
