# Generated by Django 4.2.4 on 2023-11-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='address',
            new_name='phone',
        ),
    ]
