# Generated by Django 4.2.4 on 2023-11-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0002_initial'),
        ('orders', '0003_remove_order_products_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='products', to='products.products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(related_name='carts', to='cart.cart'),
        ),
    ]
