# Generated by Django 4.2.4 on 2023-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_address_billingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'bangladesh')], null=True),
        ),
    ]
