# Generated by Django 4.2.4 on 2023-11-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product_alter_order_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
