# Generated by Django 4.2.4 on 2023-11-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_billingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='select_order_stats',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Cancle'), (3, 'Deliver'), (2, 'Pending'), (1, 'Just_order')], null=True),
        ),
    ]
