# Generated by Django 4.2.4 on 2023-11-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_select_order_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='select_order_stats',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Cancle'), (2, 'Deliver'), (1, 'Pending')], null=True),
        ),
    ]
