# Generated by Django 4.2.4 on 2023-11-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_product_item_cart_item_cart_quantity_and_more'),
        ('orders', '0006_remove_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(related_name='carts', to='cart.cart'),
        ),
    ]
