# Generated by Django 4.2.4 on 2023-11-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='select_order_stats',
        ),
    ]
