# Generated by Django 4.2.4 on 2024-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_grand_total_alter_order_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
