# Generated by Django 4.2.4 on 2023-11-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_orderitems_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_of_each_product',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
