# Generated by Django 4.2.4 on 2023-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_orderid_remove_cart_paymentid'),
        ('orders', '0009_order_final_total_order_sum_of_each_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(related_name='carts', to='cart.cart'),
        ),
    ]
