# Generated by Django 4.2.4 on 2023-11-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bangladesh')], null=True),
        ),
    ]
