# Generated by Django 4.2.4 on 2023-12-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_rename_user_name_guest_user_phone'),
        ('orders', '0013_order_guest_user_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('country', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bangladesh')], null=True)),
                ('guest_user', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.guest_user')),
            ],
        ),
    ]
