# Generated by Django 4.2.4 on 2024-01-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_gallery'),
        ('orders', '0014_alter_order_order_number_alter_order_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_Size_variant',
            field=models.ManyToManyField(blank=True, null=True, to='products.product_size_variant'),
        ),
    ]
