# Generated by Django 4.2.4 on 2024-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_product_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='each_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
