# Generated by Django 4.2.4 on 2024-02-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_products_ordered_ordered_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products_ordered',
            name='payment_number',
        ),
        migrations.AddField(
            model_name='products_ordered',
            name='ordered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
