# Generated by Django 4.2.4 on 2024-02-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_gallery'),
        ('orders', '0021_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_ordered',
            name='product_Size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product_size_variant'),
        ),
    ]
