# Generated by Django 4.2.4 on 2024-02-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_order_product_size_variant_order_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
