# Generated by Django 4.2.4 on 2023-12-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_price', models.FloatField()),
                ('product_old_price', models.FloatField()),
                ('product_discription', models.TextField()),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prand', to='product_categories.product_brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product_categories.product_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_area', models.TextField(blank=True, null=True)),
                ('commented_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_review', to='products.products')),
            ],
        ),
    ]
