# Generated by Django 4.2.4 on 2023-12-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0001_initial'),
        ('products', '0002_customer_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product_categories.product_categories'),
        ),
    ]
