# Generated by Django 4.2.4 on 2023-12-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_product_size_delete_size_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Size_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_size',
            field=models.ManyToManyField(blank=True, null=True, to='products.product_size_variant'),
        ),
    ]
