# Generated by Django 4.2.4 on 2023-12-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_size_variant_products_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Color_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
