# Generated by Django 4.2.4 on 2023-12-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_color_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.ManyToManyField(blank=True, null=True, to='products.product_color_variant'),
        ),
    ]
