# Generated by Django 4.2.4 on 2023-12-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Delivery_Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
