# Generated by Django 4.2.4 on 2023-12-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_delivery_country_products_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_delivery_country',
            field=models.ManyToManyField(blank=True, null=True, to='products.product_delivery_country'),
        ),
    ]
