# Generated by Django 4.2.4 on 2023-12-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_product_delivery_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_review',
            old_name='commented_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='customer_review',
            name='comment_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
