# Generated by Django 4.2.4 on 2024-01-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_commented_date_customer_review_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available_choose',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'in_stoke'), (2, 'out_of_stock')], null=True),
        ),
    ]
