# Generated by Django 4.2.4 on 2024-01-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_available_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shipping_fee',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Free'), (2, 'Not Free')], null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='available_choose',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'In Stoke'), (2, 'Out of Stock')], null=True),
        ),
    ]
