# Generated by Django 4.2.4 on 2024-01-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_products_shipping_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount', models.IntegerField(default=False)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('is_expired_coupon_code', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coupon Code',
            },
        ),
    ]
